services:
  floatpod:
    image: ghcr.io/pagdot/floatpod:latest
    container_name: floatpod
    restart: always
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data
      - ./config:/config
